name: Sanity
on: [push]
jobs:
  CondaBuild:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: s-weigand/setup-conda@v1.0.6
        with:
          conda-channels: conda-forge
          python-version: ${{ matrix.python-version }}
      - run: >
          conda install
          conda-build
          anaconda-client
          conda-verify
          anaconda
          $(conda --version | tr ' ' '=')
          python=${{ matrix.python-version }}
      # - run: anaconda --help
      - run: >-
          python setup.py anaconda_upload --token=xxx --package=./test/*.csv
      - run: >-
          for p in $(echo "$PATH" | tr ':' '\n') ; do
            if [ -d "$p" ] ; then
              find "$p" -type f -name 'anaconda*'
            fi
          done
